set -g focus-events on
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

bind t display-popup \
  -d "#{pane_current_path}" \
  -w "50%" \
  -h "50%"

bind u display-popup \
  -d "#{pane_current_path}" \
  -w "100" \
  -h "15" \
  -E \
  "make && gcloud compute scp bin/* ken@zeus-live-buster:~/ && echo \"\nDone!\n\"; sleep 1"

bind " " display-menu -T"#[align=center]Menu" \
  -x C -y C \
  "Networking" networking "display-popup -w 50% -h 80% -d '#{pane_current_path}' -E 'nmtui'" \
  "Blueman" blueman "run-shell blueman-manager" \
  "Fix Polybar" p "run-shell ~/.config/polybar/launch.sh --material" \
  "Edit Tmux Config" c "display-popup -w 50% -h 80% -d '#{pane_current_path}' -E 'NVIM_APPNAME=lazyvim nvim ~/.tmux.conf'; display-message 'config reloaded' ; source-file ~/.tmux.conf" \
  "Reload Config" r "source-file ~/.tmux.conf" \
  "OpenCode" o "display-popup -E opencode" \


# To copy, left click and drag to highlight text in yellow, 
# once you release left click yellow text will disappear and will automatically be available in clibboard
# # Use vim keybindings in copy mode
setw -g mode-keys vi
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

set -g @resurrect-strategy-nvim 'session'

set -g history-limit 10000
set -s exit-empty off
set -g escape-time 50
set -g status-right '#W  '
set -g monitor-activity on
set -g visual-activity both

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set-option -g default-shell /usr/bin/zsh

# nova theme config
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 
set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#50fa7b #282a36"
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#50fa7b #282a36"
set -g @nova-segments-0-left "mode"
set -g @nova-segments-1-left "session"

# tmux-agent-sidebar config
set -g @sidebar_notifications_events all

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

